package compose

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/lngstck/stackctl/internal/docker"
	"github.com/lngstck/stackctl/internal/paths"
)

// Banner is prepended to every generated docker-compose.yml.
const Banner = "# Generated by stackctl – do not edit manually.\n"

// BuildServiceBlock turns an AppDefinition into the map structure that
// yaml.Marshal will serialize as a docker-compose service entry. The
// returned map is keyed by the compose service name (ls-{id}).
func BuildServiceBlock(def *AppDefinition) map[string]any {
	svc := map[string]any{
		"image":          def.Image.FullImage(),
		"container_name": docker.ContainerName(def.ID),
		"restart":        "unless-stopped",
		"networks":       []string{docker.NetworkName},
	}

	// Ports: "{bind}:{host}:{container}"
	if len(def.Ports) > 0 {
		var portStrings []string
		for _, p := range def.Ports {
			bind := p.Bind
			if bind == "" {
				bind = "0.0.0.0"
			}
			portStrings = append(portStrings, fmt.Sprintf("%s:%d:%d", bind, p.Host, p.Container))
		}
		svc["ports"] = portStrings
	}

	// Volumes: "{host}:{container}[:ro]"
	if len(def.Volumes) > 0 {
		var volStrings []string
		for _, v := range def.Volumes {
			s := v.Host + ":" + v.Container
			if v.ReadOnly {
				s += ":ro"
			}
			volStrings = append(volStrings, s)
		}
		svc["volumes"] = volStrings
	}

	// Environment: "KEY=${PLACEHOLDER}" or "KEY=literal"
	if len(def.Environment) > 0 {
		env := map[string]string{}
		for _, e := range def.Environment {
			env[e.Key] = e.Value
		}
		svc["environment"] = env
	}

	// entrypoint + command: both exec-form lists (never shell-form). Setting
	// entrypoint bypasses the image's default — needed e.g. for dex to skip
	// the gomplate wrapper.
	if len(def.Entrypoint) > 0 {
		svc["entrypoint"] = append([]string{}, def.Entrypoint...)
	}
	if len(def.Command) > 0 {
		svc["command"] = append([]string{}, def.Command...)
	}

	// depends_on: ["ls-postgres", "ls-dex", ...]
	if len(def.DependsOn) > 0 {
		var deps []string
		for _, d := range def.DependsOn {
			deps = append(deps, docker.ContainerName(d))
		}
		svc["depends_on"] = deps
	}

	return svc
}

// Regenerate builds a complete docker-compose.yml from the set of currently
// installed app definitions and writes it atomically to paths.ComposeFile().
//
// The definitions slice may be in any order — they're sorted by ID for a
// stable output.
func Regenerate(defs []*AppDefinition) error {
	// Sort for deterministic output.
	sorted := make([]*AppDefinition, len(defs))
	copy(sorted, defs)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].ID < sorted[j].ID
	})

	services := map[string]any{}
	for _, def := range sorted {
		svc := BuildServiceBlock(def)
		services[docker.ContainerName(def.ID)] = svc
	}

	doc := map[string]any{
		"networks": map[string]any{
			docker.NetworkName: map[string]any{
				"external": true,
			},
		},
	}
	if len(services) > 0 {
		doc["services"] = services
	}

	data, err := yaml.Marshal(doc)
	if err != nil {
		return fmt.Errorf("compose: marshal: %w", err)
	}

	out := Banner + string(data)
	return paths.AtomicWrite(paths.ComposeFile(), []byte(out), 0o644)
}

// ServiceName returns the compose service name for an app ID.
func ServiceName(appID string) string {
	return docker.ContainerName(appID)
}

// ParseServiceEnv extracts the environment block from a compose service
// definition for debugging / display. This is a convenience — the actual
// values live in .env, not in the compose file.
func ParseServiceEnv(svc map[string]any) map[string]string {
	out := map[string]string{}
	raw, ok := svc["environment"]
	if !ok {
		return out
	}
	switch v := raw.(type) {
	case map[string]any:
		for k, val := range v {
			out[k] = fmt.Sprint(val)
		}
	case map[string]string:
		for k, val := range v {
			out[k] = val
		}
	}
	return out
}

// EnvRef returns the docker-compose variable reference form "${KEY}".
func EnvRef(key string) string {
	return "${" + key + "}"
}

// AppIDFromContainer extracts the app ID from a container name.
// Returns ("", false) if the name doesn't have the ls- prefix.
func AppIDFromContainer(name string) (string, bool) {
	if !strings.HasPrefix(name, docker.ContainerPrefix) {
		return "", false
	}
	return strings.TrimPrefix(name, docker.ContainerPrefix), true
}
