package caddy

import (
	"os"
	"strings"
	"testing"

	"github.com/lngstck/stackctl/internal/config"
	"github.com/lngstck/stackctl/internal/paths"
)

func testCfg() *config.Config {
	return &config.Config{
		School: config.School{Slug: "phoenix"},
		Public: config.Public{
			Transport:  config.TransportDirect,
			BaseDomain: "ls.gym-phoenix.de",
			Direct:     config.PublicDirect{ACMEEmail: "admin@gym-phoenix.de"},
		},
	}
}

func TestGenerateConfig(t *testing.T) {
	got := string(GenerateConfig(testCfg(), []Route{
		{Host: "pylearn.ls.gym-phoenix.de", Upstream: "ls-pylearn:8000"},
		{Host: "auth.ls.gym-phoenix.de", Upstream: "ls-dex:5556"},
	}))

	want := `# Generated by stackctl – do not edit manually.
{
	email admin@gym-phoenix.de
}

auth.ls.gym-phoenix.de {
	reverse_proxy ls-dex:5556
}

pylearn.ls.gym-phoenix.de {
	reverse_proxy ls-pylearn:8000
}
`
	if got != want {
		t.Errorf("Caddyfile mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// Output must not depend on the order routes arrive in — otherwise every
// regeneration would look like a change and force a needless reload.
func TestGenerateConfigIsStable(t *testing.T) {
	cfg := testCfg()
	a := GenerateConfig(cfg, []Route{
		{Host: "a.example.org", Upstream: "ls-a:1"},
		{Host: "b.example.org", Upstream: "ls-b:2"},
	})
	b := GenerateConfig(cfg, []Route{
		{Host: "b.example.org", Upstream: "ls-b:2"},
		{Host: "a.example.org", Upstream: "ls-a:1"},
	})
	if string(a) != string(b) {
		t.Error("route order changed the output")
	}
}

func TestGenerateConfigWithoutGlobalOptions(t *testing.T) {
	cfg := testCfg()
	cfg.Public.Direct = config.PublicDirect{}

	got := string(GenerateConfig(cfg, []Route{{Host: "a.example.org", Upstream: "ls-a:1"}}))

	// No email and no CA override means no global block at all — an empty
	// "{ }" is a syntax error in a Caddyfile.
	if strings.Contains(got, "{\n}") {
		t.Errorf("emitted an empty global block:\n%s", got)
	}
	if !strings.Contains(got, "a.example.org {") {
		t.Errorf("missing site block:\n%s", got)
	}
}

// The staging CA exists precisely so debugging does not burn through Let's
// Encrypt's five-duplicates-per-week limit.
func TestGenerateConfigStagingCA(t *testing.T) {
	cfg := testCfg()
	cfg.Public.Direct.ACMECA = "https://acme-staging-v02.api.letsencrypt.org/directory"

	got := string(GenerateConfig(cfg, nil))
	if !strings.Contains(got, "acme_ca https://acme-staging-v02.api.letsencrypt.org/directory") {
		t.Errorf("staging CA not honoured:\n%s", got)
	}
}

func TestGenerateConfigSkipsIncompleteRoutes(t *testing.T) {
	got := string(GenerateConfig(testCfg(), []Route{
		{Host: "", Upstream: "ls-a:1"},
		{Host: "b.example.org", Upstream: ""},
		{Host: "c.example.org", Upstream: "ls-c:3"},
	}))
	if strings.Count(got, "reverse_proxy") != 1 {
		t.Errorf("incomplete routes must not be emitted:\n%s", got)
	}
}

// Apply must report "unchanged" for identical input, so callers can skip the
// reload. Writing the same bytes again would otherwise reload the proxy — and
// re-plan every site — on every publish operation.
func TestApplyDetectsUnchangedConfig(t *testing.T) {
	t.Setenv(paths.EnvLearningstackDir, t.TempDir())
	cfg := testCfg()
	routes := []Route{{Host: "a.example.org", Upstream: "ls-a:1"}}

	changed, err := Apply(cfg, routes)
	if err != nil {
		t.Fatalf("first Apply: %v", err)
	}
	if !changed {
		t.Error("first Apply should report a change")
	}

	changed, err = Apply(cfg, routes)
	if err != nil {
		t.Fatalf("second Apply: %v", err)
	}
	if changed {
		t.Error("identical config should not report a change")
	}

	data, err := os.ReadFile(paths.CaddyConfigFile())
	if err != nil {
		t.Fatalf("read Caddyfile: %v", err)
	}
	if !strings.Contains(string(data), "a.example.org") {
		t.Errorf("Caddyfile not written as expected:\n%s", data)
	}

	// A different route set is a change again.
	changed, err = Apply(cfg, append(routes, Route{Host: "b.example.org", Upstream: "ls-b:2"}))
	if err != nil || !changed {
		t.Errorf("adding a route: changed=%v err=%v", changed, err)
	}
}

func TestUpstream(t *testing.T) {
	if got, want := Upstream("pylearn", 8000), "ls-pylearn:8000"; got != want {
		t.Errorf("Upstream = %q, want %q", got, want)
	}
}
