// Copyright (C) 2026 learningstack contributors. Licensed under AGPL-3.0-or-later. See LICENSE.

// Package caddy generates and applies the Caddyfile, and is the counterpart
// to internal/dex: stackctl owns the file completely and rewrites it in full
// on every change.
//
// Caddy earns its place here for one reason above the others — it obtains and
// renews the TLS certificates on its own. In the school network that is one
// wildcard certificate over DNS-01 (the certificate authority never reaches a
// private address); on a server directly on the internet it is one
// certificate per hostname over HTTP-01. Either way there is no acme.sh, no
// cron job and no reload hook. The second reason is the ports: without a
// proxy every app would have to be reached on its own high port, unencrypted.
package caddy

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/lngstck/stackctl/internal/config"
	"github.com/lngstck/stackctl/internal/docker"
	"github.com/lngstck/stackctl/internal/paths"
)

// ContainerName is the Docker container name of the reverse proxy.
const ContainerName = "ls-caddy"

// ConfigPathInContainer is where the bind mount makes the Caddyfile visible.
// It must match the command: in the catalog definition.
const ConfigPathInContainer = "/etc/caddy/Caddyfile"

// DNSTokenEnv is the environment variable the proxy reads the deSEC token
// from. The catalog definition passes it through from .env.
const DNSTokenEnv = "DESEC_TOKEN"

// Route is one published hostname and the container behind it.
type Route struct {
	// Host is the public FQDN, e.g. "pylearn.ls.gym-phoenix.de".
	Host string
	// Upstream is the address Caddy proxies to, e.g. "ls-pylearn:8000".
	// Caddy shares the app network, so it addresses containers by name and
	// never needs a published host port.
	Upstream string
}

// Upstream builds the proxy target for an app container.
func Upstream(appID string, containerPort int) string {
	return fmt.Sprintf("%s:%d", docker.ContainerName(appID), containerPort)
}

// GenerateConfig renders the Caddyfile for the given routes.
//
// Routes are sorted by host so the output is stable: an unchanged set of apps
// must produce a byte-identical file, otherwise every regeneration would look
// like a change and trigger a pointless reload.
func GenerateConfig(cfg *config.Config, routes []Route) []byte {
	var b strings.Builder

	b.WriteString("# Generated by stackctl – do not edit manually.\n")

	// Global options block. Caddy only accepts one, and it must come first.
	var global []string
	if email := cfg.Public.ACMEEmail; email != "" {
		global = append(global, "\temail "+email)
	}
	if ca := cfg.Public.ACMECA; ca != "" {
		global = append(global, "\tacme_ca "+ca)
	}
	if len(global) > 0 {
		b.WriteString("{\n")
		b.WriteString(strings.Join(global, "\n"))
		b.WriteString("\n}\n")
	}

	var sorted []Route
	for _, r := range routes {
		if r.Host != "" && r.Upstream != "" {
			sorted = append(sorted, r)
		}
	}
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Host < sorted[j].Host })

	if cfg.Public.Transport == config.TransportLocal {
		writeWildcardSite(&b, cfg, sorted)
	} else {
		writeSites(&b, sorted)
	}

	return []byte(b.String())
}

// writeSites gives every host its own site block. Caddy then obtains one
// certificate per host over HTTP-01, which needs port 80 reachable from the
// internet.
func writeSites(b *strings.Builder, routes []Route) {
	for _, r := range routes {
		b.WriteString("\n")
		fmt.Fprintf(b, "%s {\n", r.Host)
		fmt.Fprintf(b, "\treverse_proxy %s\n", r.Upstream)
		b.WriteString("}\n")
	}
}

// dnsPropagationDelay is how long Caddy waits after writing the challenge
// record before asking the CA to look (see writeWildcardSite).
const dnsPropagationDelay = "5m"

// writeWildcardSite serves every host from one wildcard site with a single
// certificate obtained over DNS-01. One certificate means one challenge name,
// so the school delegates exactly one record — and a newly installed app
// needs no new certificate at all.
//
// The site is written even without routes: the certificate is the slow part,
// and having it before the first app is installed is the point.
func writeWildcardSite(b *strings.Builder, cfg *config.Config, routes []Route) {
	base := cfg.Public.BaseDomain
	if base == "" {
		return
	}

	b.WriteString("\n")
	fmt.Fprintf(b, "*.%s {\n", base)
	b.WriteString("\ttls {\n")
	b.WriteString("\t\tdns desec {\n")
	fmt.Fprintf(b, "\t\t\ttoken {env.%s}\n", DNSTokenEnv)
	b.WriteString("\t\t}\n")
	if target := cfg.Public.Local.ChallengeDomain; target != "" {
		fmt.Fprintf(b, "\t\tdns_challenge_override_domain %s\n", target)
	}
	// deSEC verteilt einen neuen Eintrag nicht überall gleich schnell:
	// Die meisten Knoten haben ihn nach Sekunden, einzelne erst nach knapp
	// drei Minuten (bekannt, talk.desec.io/t/1790). Let's Encrypt prüft von
	// mehreren Standorten; trifft einer einen Nachzügler, scheitert die
	// Prüfung und Caddy räumt den Eintrag wieder weg. Auf test1 am
	// 2026-10-10 mit 0 und mit 2 Minuten Wartezeit gesehen.
	fmt.Fprintf(b, "\t\tpropagation_delay %s\n", dnsPropagationDelay)
	b.WriteString("\t}\n")

	for _, r := range routes {
		// The matcher is named after the first label, which is unique below
		// the base domain: an app id, "auth" or "admin".
		name := strings.SplitN(r.Host, ".", 2)[0]
		b.WriteString("\n")
		fmt.Fprintf(b, "\t@%s host %s\n", name, r.Host)
		fmt.Fprintf(b, "\thandle @%s {\n", name)
		fmt.Fprintf(b, "\t\treverse_proxy %s\n", r.Upstream)
		b.WriteString("\t}\n")
	}

	// Every name under the base resolves here, published or not. A plain
	// answer beats Caddy's empty 200 for a typo or an app that was removed.
	b.WriteString("\n")
	b.WriteString("\thandle {\n")
	b.WriteString("\t\trespond \"Unbekannte Adresse\" 404\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")
}

// Apply writes the Caddyfile and makes the running proxy pick it up.
//
// It returns true when the file changed. An unchanged file skips the reload:
// Caddy re-validates and re-plans its whole config on every reload, and
// publishing one app should not disturb the other sites.
func Apply(cfg *config.Config, routes []Route) (changed bool, err error) {
	data := GenerateConfig(cfg, routes)

	if err := paths.EnsureDir(filepath.Dir(paths.CaddyConfigFile()), 0o755); err != nil {
		return false, err
	}
	same, err := fileHasContent(paths.CaddyConfigFile(), data)
	if err != nil {
		return false, err
	}
	if same {
		return false, nil
	}
	// 0644: the proxy runs as its own user inside the container and has to
	// read this. Same reasoning as dex-config.yaml — on a single-tenant
	// server the file holds no secrets anyway.
	if err := paths.AtomicWrite(paths.CaddyConfigFile(), data, 0o644); err != nil {
		return false, err
	}

	// A stopped proxy is not an error: it reads the file when it starts. This
	// is the normal case during installation, before the container exists.
	if !docker.IsRunning(ContainerName) {
		return true, nil
	}
	return true, Reload()
}

// Reload asks the running proxy to adopt the config on disk.
//
// A rejected config leaves the previous one running — Caddy validates before
// it swaps. That is what makes regenerating the whole file safe: a mistake
// costs the new route, not every site already being served.
func Reload() error {
	code, out, err := docker.Exec(ContainerName, []string{
		"caddy", "reload", "--config", ConfigPathInContainer, "--adapter", "caddyfile",
	})
	if err != nil {
		return fmt.Errorf("caddy: reload: %w", err)
	}
	if code != 0 {
		return fmt.Errorf("caddy: reload rejected the config (exit %d): %s", code, strings.TrimSpace(out))
	}
	return nil
}

// IsRunning reports whether the reverse proxy container is up. Without it
// nothing published this way is reachable, however correct the config is.
func IsRunning() bool { return docker.IsRunning(ContainerName) }

// fileHasContent reports whether path already holds exactly want.
func fileHasContent(path string, want []byte) (bool, error) {
	got, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return false, nil
		}
		return false, err
	}
	return bytes.Equal(got, want), nil
}
