package caddy

import (
	"os"
	"strings"
	"testing"

	"github.com/lngstck/stackctl/internal/config"
	"github.com/lngstck/stackctl/internal/paths"
)

func testCfg() *config.Config {
	return &config.Config{
		School: config.School{Slug: "phoenix"},
		Public: config.Public{
			Transport:  config.TransportDirect,
			BaseDomain: "ls.gym-phoenix.de",
			ACMEEmail:  "admin@gym-phoenix.de",
		},
	}
}

func TestGenerateConfig(t *testing.T) {
	got := string(GenerateConfig(testCfg(), []Route{
		{Host: "pylearn.ls.gym-phoenix.de", Upstream: "ls-pylearn:8000"},
		{Host: "auth.ls.gym-phoenix.de", Upstream: "ls-dex:5556"},
	}))

	want := `# Generated by stackctl – do not edit manually.
{
	email admin@gym-phoenix.de
}

auth.ls.gym-phoenix.de {
	reverse_proxy ls-dex:5556
}

pylearn.ls.gym-phoenix.de {
	reverse_proxy ls-pylearn:8000
}
`
	if got != want {
		t.Errorf("Caddyfile mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// Output must not depend on the order routes arrive in — otherwise every
// regeneration would look like a change and force a needless reload.
func TestGenerateConfigIsStable(t *testing.T) {
	cfg := testCfg()
	a := GenerateConfig(cfg, []Route{
		{Host: "a.example.org", Upstream: "ls-a:1"},
		{Host: "b.example.org", Upstream: "ls-b:2"},
	})
	b := GenerateConfig(cfg, []Route{
		{Host: "b.example.org", Upstream: "ls-b:2"},
		{Host: "a.example.org", Upstream: "ls-a:1"},
	})
	if string(a) != string(b) {
		t.Error("route order changed the output")
	}
}

func TestGenerateConfigWithoutGlobalOptions(t *testing.T) {
	cfg := testCfg()
	cfg.Public.ACMEEmail = ""

	got := string(GenerateConfig(cfg, []Route{{Host: "a.example.org", Upstream: "ls-a:1"}}))

	// No email and no CA override means no global block at all — an empty
	// "{ }" is a syntax error in a Caddyfile.
	if strings.Contains(got, "{\n}") {
		t.Errorf("emitted an empty global block:\n%s", got)
	}
	if !strings.Contains(got, "a.example.org {") {
		t.Errorf("missing site block:\n%s", got)
	}
}

// The staging CA exists precisely so debugging does not burn through Let's
// Encrypt's five-duplicates-per-week limit.
func TestGenerateConfigStagingCA(t *testing.T) {
	cfg := testCfg()
	cfg.Public.ACMECA = "https://acme-staging-v02.api.letsencrypt.org/directory"

	got := string(GenerateConfig(cfg, nil))
	if !strings.Contains(got, "acme_ca https://acme-staging-v02.api.letsencrypt.org/directory") {
		t.Errorf("staging CA not honoured:\n%s", got)
	}
}

func TestGenerateConfigSkipsIncompleteRoutes(t *testing.T) {
	got := string(GenerateConfig(testCfg(), []Route{
		{Host: "", Upstream: "ls-a:1"},
		{Host: "b.example.org", Upstream: ""},
		{Host: "c.example.org", Upstream: "ls-c:3"},
	}))
	if strings.Count(got, "reverse_proxy") != 1 {
		t.Errorf("incomplete routes must not be emitted:\n%s", got)
	}
}

// Apply must report "unchanged" for identical input, so callers can skip the
// reload. Writing the same bytes again would otherwise reload the proxy — and
// re-plan every site — on every publish operation.
func TestApplyDetectsUnchangedConfig(t *testing.T) {
	t.Setenv(paths.EnvLearningstackDir, t.TempDir())
	cfg := testCfg()
	routes := []Route{{Host: "a.example.org", Upstream: "ls-a:1"}}

	changed, err := Apply(cfg, routes)
	if err != nil {
		t.Fatalf("first Apply: %v", err)
	}
	if !changed {
		t.Error("first Apply should report a change")
	}

	changed, err = Apply(cfg, routes)
	if err != nil {
		t.Fatalf("second Apply: %v", err)
	}
	if changed {
		t.Error("identical config should not report a change")
	}

	data, err := os.ReadFile(paths.CaddyConfigFile())
	if err != nil {
		t.Fatalf("read Caddyfile: %v", err)
	}
	if !strings.Contains(string(data), "a.example.org") {
		t.Errorf("Caddyfile not written as expected:\n%s", data)
	}

	// A different route set is a change again.
	changed, err = Apply(cfg, append(routes, Route{Host: "b.example.org", Upstream: "ls-b:2"}))
	if err != nil || !changed {
		t.Errorf("adding a route: changed=%v err=%v", changed, err)
	}
}

func localCfg() *config.Config {
	cfg := testCfg()
	cfg.Public.Transport = config.TransportLocal
	cfg.Public.Local = config.PublicLocal{
		DNSToken:        "geheim",
		ChallengeDomain: "_acme-challenge.gym-phoenix.dedyn.io",
	}
	return cfg
}

// Im Schulnetz erreicht die CA den Server nie. Ein Wildcard-Block mit DNS-01
// holt das eine Zertifikat, die Hosts werden darin per Matcher verteilt.
func TestGenerateConfigLocalWildcard(t *testing.T) {
	got := string(GenerateConfig(localCfg(), []Route{
		{Host: "pylearn.ls.gym-phoenix.de", Upstream: "ls-pylearn:8000"},
		{Host: "auth.ls.gym-phoenix.de", Upstream: "ls-dex:5556"},
	}))

	want := `# Generated by stackctl – do not edit manually.
{
	email admin@gym-phoenix.de
}

*.ls.gym-phoenix.de {
	tls {
		dns desec {
			token {env.DESEC_TOKEN}
		}
		dns_challenge_override_domain _acme-challenge.gym-phoenix.dedyn.io
	}

	@auth host auth.ls.gym-phoenix.de
	handle @auth {
		reverse_proxy ls-dex:5556
	}

	@pylearn host pylearn.ls.gym-phoenix.de
	handle @pylearn {
		reverse_proxy ls-pylearn:8000
	}

	handle {
		respond "Unbekannte Adresse" 404
	}
}
`
	if got != want {
		t.Errorf("Caddyfile mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// Das Caddyfile ist fuer alle lesbar (0644). Der Token darf darin nie stehen,
// nur der Verweis auf die Umgebungsvariable.
func TestGenerateConfigLocalKeepsTokenOutOfFile(t *testing.T) {
	got := string(GenerateConfig(localCfg(), nil))
	if strings.Contains(got, "geheim") {
		t.Errorf("DNS-Token steht im Caddyfile:\n%s", got)
	}
	// Ohne Routen trotzdem den Wildcard-Block: das Zertifikat soll da sein,
	// bevor die erste App installiert wird.
	if !strings.Contains(got, "*.ls.gym-phoenix.de {") {
		t.Errorf("Wildcard-Block fehlt ohne Routen:\n%s", got)
	}
}

// Ohne Delegation verwaltet deSEC die Zone der Basis-Domain selbst; dann gibt
// es nichts umzulenken.
func TestGenerateConfigLocalWithoutDelegation(t *testing.T) {
	cfg := localCfg()
	cfg.Public.Local.ChallengeDomain = ""
	got := string(GenerateConfig(cfg, nil))
	if strings.Contains(got, "dns_challenge_override_domain") {
		t.Errorf("Override ohne Delegation:\n%s", got)
	}
}

func TestUpstream(t *testing.T) {
	if got, want := Upstream("pylearn", 8000), "ls-pylearn:8000"; got != want {
		t.Errorf("Upstream = %q, want %q", got, want)
	}
}
