package config

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lngstck/stackctl/internal/paths"
)

// withTempStackctlDir points STACKCTL_DIR at a fresh tempdir for the test.
func withTempStackctlDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	t.Setenv(paths.EnvStackctlDir, dir)
	return dir
}

func TestDefaultConfig(t *testing.T) {
	c := Default()
	if c.Version != ConfigVersion {
		t.Errorf("version = %d, want %d", c.Version, ConfigVersion)
	}
	if c.SetupState != SetupStateNeedsSetup {
		t.Errorf("SetupState = %q, want %q", c.SetupState, SetupStateNeedsSetup)
	}
	if c.Catalog.URL == "" {
		t.Error("Catalog.URL empty in default")
	}
	// Nur im Schulnetz ist der Standard: nichts verlaesst das Schulnetz
	// ohne ausdrueckliche Entscheidung.
	if c.Public.Transport != TransportLocal {
		t.Errorf("Public.Transport = %q, want %q", c.Public.Transport, TransportLocal)
	}
}

func TestLoadMissingReturnsNotExist(t *testing.T) {
	withTempStackctlDir(t)
	_, err := Load()
	if !errors.Is(err, os.ErrNotExist) {
		t.Errorf("expected os.ErrNotExist, got %v", err)
	}
}

func TestSaveAndReload(t *testing.T) {
	withTempStackctlDir(t)

	c := Default()
	c.School = School{
		Name:         "Gymnasium Phoenix",
		Slug:         "phoenix",
		ServerDomain: "192.168.1.10",
		ContactEmail: "admin@gym-phoenix.de",
	}
	c.SetupState = SetupStateReady
	c.Admin.PasswordHash = "$2a$10$abcdef"
	c.Public.BaseDomain = "ls.gym-phoenix.de"
	if err := c.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	// File must exist with 0640 perm.
	info, err := os.Stat(paths.ConfigFile())
	if err != nil {
		t.Fatalf("Stat: %v", err)
	}
	if perm := info.Mode().Perm(); perm != FilePerm {
		t.Errorf("perm = %o, want %o", perm, FilePerm)
	}

	raw, _ := os.ReadFile(paths.ConfigFile())
	if !strings.HasPrefix(string(raw), "# Generated by stackctl") {
		t.Errorf("banner missing, got: %s", string(raw)[:40])
	}

	loaded, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if loaded.School.Slug != "phoenix" {
		t.Errorf("slug round-trip failed: %q", loaded.School.Slug)
	}
	if loaded.SetupState != SetupStateReady {
		t.Errorf("SetupState round-trip: %q", loaded.SetupState)
	}
	if loaded.Public.BaseDomain != "ls.gym-phoenix.de" {
		t.Errorf("BaseDomain round-trip: %q", loaded.Public.BaseDomain)
	}
}

func TestValidate(t *testing.T) {
	c := Default() // needs_setup, no school data — should pass.
	if err := c.Validate(); err != nil {
		t.Errorf("fresh default should validate: %v", err)
	}

	c.SetupState = SetupStateReady
	if err := c.Validate(); err == nil {
		t.Error("ready without slug/name should fail")
	}

	c.School.Slug = "phoenix"
	c.School.Name = "Phoenix"
	if err := c.Validate(); err == nil {
		t.Error("ready without base_domain should fail")
	}

	c.Public.BaseDomain = "ls.gym-phoenix.de"
	if err := c.Validate(); err != nil {
		t.Errorf("ready with valid school should pass: %v", err)
	}

	// The relay is gone; a config that still names it must not pass as
	// valid, or the install would come up with nothing that publishes it.
	for _, tr := range []string{"carrier-pigeon", "relay"} {
		c.Public.Transport = tr
		if err := c.Validate(); err == nil {
			t.Errorf("transport %q should fail", tr)
		}
	}
	for _, tr := range []string{TransportLocal, TransportDirect} {
		c.Public.Transport = tr
		if err := c.Validate(); err != nil {
			t.Errorf("transport %q should validate: %v", tr, err)
		}
	}

	c.Public.BaseDomain = "https://ls.gym-phoenix.de"
	if err := c.Validate(); err == nil {
		t.Error("base_domain with scheme should fail")
	}
	c.Public.BaseDomain = "ls.gym-phoenix.de"

	c.Version = 999
	if err := c.Validate(); err == nil {
		t.Error("bad version should fail")
	}
}

func TestStateRoundTrip(t *testing.T) {
	withTempStackctlDir(t)

	s := NewState()
	s.Containers["postgres"] = &ContainerState{
		ID:               "postgres",
		Name:             "PostgreSQL",
		VersionInstalled: "16.2",
		Ports:            []int{8100},
		EnvKeys:          []string{"POSTGRES_PASSWORD"},
		InstalledAt:      "2026-04-09T12:34:00Z",
	}
	s.Ports[8100] = "postgres"

	if err := s.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	// Verify file landed under config/.
	if _, err := os.Stat(filepath.Join(paths.ConfigDir(), "state.yaml")); err != nil {
		t.Fatalf("state.yaml not found: %v", err)
	}

	loaded, err := LoadState()
	if err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	if !loaded.IsInstalled("postgres") {
		t.Error("postgres should be installed")
	}
	if owner := loaded.PortOwner(8100); owner != "postgres" {
		t.Errorf("PortOwner(8100) = %q, want postgres", owner)
	}
	ids := loaded.InstalledIDs()
	if len(ids) != 1 || ids[0] != "postgres" {
		t.Errorf("InstalledIDs = %v", ids)
	}
}

func TestLoadStateMissingReturnsEmpty(t *testing.T) {
	withTempStackctlDir(t)
	s, err := LoadState()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(s.Containers) != 0 {
		t.Errorf("containers = %d, want 0", len(s.Containers))
	}
	if s.Version != StateVersion {
		t.Errorf("version = %q, want %q", s.Version, StateVersion)
	}
}

func writeConfigFile(t *testing.T, content string) {
	t.Helper()
	if err := os.MkdirAll(paths.ConfigDir(), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(paths.ConfigFile(), []byte(content), 0o640); err != nil {
		t.Fatal(err)
	}
}

// global_env was never read by anything — the map existed, was kept non-nil,
// and no code path ever looked at it. Removing the field means an existing
// block is ignored on load and dropped on the next save. That is deliberate:
// a key sitting in config.yaml that looks like configuration but does nothing
// is worse than no key at all. The live LLM_API_KEY lives in .env.
func TestLoadIgnoresRemovedGlobalEnv(t *testing.T) {
	withTempStackctlDir(t)
	writeConfigFile(t, `version: 4
setup_state: ready
school:
    slug: phoenix
public:
    transport: direct
    base_domain: ls.gym-phoenix.de
global_env:
    LLM_ENDPOINT: https://api.openai.com/v1
    LLM_API_KEY: sk-alt
`)

	c, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if err := c.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	raw, err := os.ReadFile(paths.ConfigFile())
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(raw), "global_env") {
		t.Errorf("global_env survived the rewrite:\n%s", raw)
	}
	// The rest of the file has to be intact — this is a dropped field, not a
	// dropped file.
	if c.Public.BaseDomain != "ls.gym-phoenix.de" {
		t.Errorf("BaseDomain = %q", c.Public.BaseDomain)
	}
}
