package config

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lngstck/stackctl/internal/paths"
)

// withTempStackctlDir points STACKCTL_DIR at a fresh tempdir for the test.
func withTempStackctlDir(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	t.Setenv(paths.EnvStackctlDir, dir)
	return dir
}

func TestDefaultConfig(t *testing.T) {
	c := Default()
	if c.Version != ConfigVersion {
		t.Errorf("version = %d, want %d", c.Version, ConfigVersion)
	}
	if c.SetupState != SetupStateNeedsSetup {
		t.Errorf("SetupState = %q, want %q", c.SetupState, SetupStateNeedsSetup)
	}
	if c.Catalog.URL == "" {
		t.Error("Catalog.URL empty in default")
	}
	if c.Public.Transport != TransportRelay {
		t.Errorf("Public.Transport = %q, want %q", c.Public.Transport, TransportRelay)
	}
	if c.Public.Relay.SSHHost != "sish.learningstack.online" {
		t.Errorf("Public.Relay.SSHHost = %q", c.Public.Relay.SSHHost)
	}
	if c.Public.Relay.SSHPort != 2222 {
		t.Errorf("Public.Relay.SSHPort = %d, want 2222", c.Public.Relay.SSHPort)
	}
	if c.GlobalEnv == nil {
		t.Error("GlobalEnv should be non-nil map")
	}
}

func TestLoadMissingReturnsNotExist(t *testing.T) {
	withTempStackctlDir(t)
	_, err := Load()
	if !errors.Is(err, os.ErrNotExist) {
		t.Errorf("expected os.ErrNotExist, got %v", err)
	}
}

func TestSaveAndReload(t *testing.T) {
	withTempStackctlDir(t)

	c := Default()
	c.School = School{
		Name:         "Gymnasium Phoenix",
		Slug:         "phoenix",
		ServerDomain: "192.168.1.10",
		ContactEmail: "admin@gym-phoenix.de",
	}
	c.SetupState = SetupStateReady
	c.Admin.PasswordHash = "$2a$10$abcdef"
	c.Dex = Dex{
		ClientID:     "phoenix",
		ClientSecret: "deadbeef",
	}
	c.GlobalEnv["LLM_ENDPOINT"] = "https://llm.example/v1"

	if err := c.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	// File must exist with 0640 perm.
	info, err := os.Stat(paths.ConfigFile())
	if err != nil {
		t.Fatalf("Stat: %v", err)
	}
	if perm := info.Mode().Perm(); perm != FilePerm {
		t.Errorf("perm = %o, want %o", perm, FilePerm)
	}

	raw, _ := os.ReadFile(paths.ConfigFile())
	if !strings.HasPrefix(string(raw), "# Generated by stackctl") {
		t.Errorf("banner missing, got: %s", string(raw)[:40])
	}

	loaded, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if loaded.School.Slug != "phoenix" {
		t.Errorf("slug round-trip failed: %q", loaded.School.Slug)
	}
	if loaded.SetupState != SetupStateReady {
		t.Errorf("SetupState round-trip: %q", loaded.SetupState)
	}
	if loaded.Dex.ClientSecret != "deadbeef" {
		t.Errorf("Dex.ClientSecret round-trip: %q", loaded.Dex.ClientSecret)
	}
	if loaded.GlobalEnv["LLM_ENDPOINT"] != "https://llm.example/v1" {
		t.Errorf("GlobalEnv round-trip failed")
	}
}

func TestValidate(t *testing.T) {
	c := Default() // needs_setup, no school data — should pass.
	if err := c.Validate(); err != nil {
		t.Errorf("fresh default should validate: %v", err)
	}

	c.SetupState = SetupStateReady
	if err := c.Validate(); err == nil {
		t.Error("ready without slug/name should fail")
	}

	c.School.Slug = "phoenix"
	c.School.Name = "Phoenix"
	if err := c.Validate(); err == nil {
		t.Error("ready without base_domain should fail")
	}

	c.Public.BaseDomain = RelayBaseDomain("phoenix")
	if err := c.Validate(); err != nil {
		t.Errorf("ready with valid school should pass: %v", err)
	}

	c.Public.Transport = "carrier-pigeon"
	if err := c.Validate(); err == nil {
		t.Error("unknown transport should fail")
	}
	c.Public.Transport = TransportDirect
	if err := c.Validate(); err != nil {
		t.Errorf("direct transport should validate: %v", err)
	}
	c.Public.Transport = TransportRelay

	c.Public.BaseDomain = "https://ls.gym-phoenix.de"
	if err := c.Validate(); err == nil {
		t.Error("base_domain with scheme should fail")
	}
	c.Public.BaseDomain = RelayBaseDomain("phoenix")

	c.Version = 999
	if err := c.Validate(); err == nil {
		t.Error("bad version should fail")
	}
}

func TestStateRoundTrip(t *testing.T) {
	withTempStackctlDir(t)

	s := NewState()
	s.Containers["postgres"] = &ContainerState{
		ID:               "postgres",
		Name:             "PostgreSQL",
		VersionInstalled: "16.2",
		Ports:            []int{8100},
		EnvKeys:          []string{"POSTGRES_PASSWORD"},
		InstalledAt:      "2026-04-09T12:34:00Z",
	}
	s.Ports[8100] = "postgres"

	if err := s.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	// Verify file landed under config/.
	if _, err := os.Stat(filepath.Join(paths.ConfigDir(), "state.yaml")); err != nil {
		t.Fatalf("state.yaml not found: %v", err)
	}

	loaded, err := LoadState()
	if err != nil {
		t.Fatalf("LoadState: %v", err)
	}
	if !loaded.IsInstalled("postgres") {
		t.Error("postgres should be installed")
	}
	if owner := loaded.PortOwner(8100); owner != "postgres" {
		t.Errorf("PortOwner(8100) = %q, want postgres", owner)
	}
	ids := loaded.InstalledIDs()
	if len(ids) != 1 || ids[0] != "postgres" {
		t.Errorf("InstalledIDs = %v", ids)
	}
}

func TestLoadStateMissingReturnsEmpty(t *testing.T) {
	withTempStackctlDir(t)
	s, err := LoadState()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(s.Containers) != 0 {
		t.Errorf("containers = %d, want 0", len(s.Containers))
	}
	if s.Version != StateVersion {
		t.Errorf("version = %q, want %q", s.Version, StateVersion)
	}
}

// v2File is a config.yaml exactly as stackctl v0.10.1 wrote it: no public:
// section, the relay endpoint in a top-level tunnel: block, and a stored
// dex.auth_url that today's build derives instead.
const v2File = `# Generated by stackctl – edit via the admin web UI or stackctl CLI.
version: 2
setup_state: ready
school:
    name: Testschule
    slug: testschulev02
    server_domain: 192.168.1.50
catalog:
    url: https://raw.githubusercontent.com/lngstck/catalog/main
admin:
    password_hash: $2a$10$abcdefghijklmnopqrstuv
dex:
    client_id: testschulev02
    client_secret: deadbeef
    auth_url: https://auth.testschulev02.learningstack.online
tunnel:
    ssh_host: sish.learningstack.online
    ssh_port: 2222
auto_update:
    enabled: true
`

// A v2 file has to come back as a working relay install. Losing the endpoint
// here is not a cosmetic defect: ssh would dial port 0, the login tunnel would
// never come up, and the school would be offline after a routine self-update.
func TestLoadUpgradesV2Config(t *testing.T) {
	withTempStackctlDir(t)
	writeConfigFile(t, v2File)

	c, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}

	if c.Version != ConfigVersion {
		t.Errorf("Version = %d, want %d", c.Version, ConfigVersion)
	}
	if c.Public.Transport != TransportRelay {
		t.Errorf("Transport = %q, want %q — every v2 install was a relay install", c.Public.Transport, TransportRelay)
	}
	if want := "testschulev02.learningstack.online"; c.Public.BaseDomain != want {
		t.Errorf("BaseDomain = %q, want %q", c.Public.BaseDomain, want)
	}
	if want := "sish.learningstack.online"; c.Public.Relay.SSHHost != want {
		t.Errorf("Relay.SSHHost = %q, want %q — taken from the old tunnel: block", c.Public.Relay.SSHHost, want)
	}
	if c.Public.Relay.SSHPort != 2222 {
		t.Errorf("Relay.SSHPort = %d, want 2222", c.Public.Relay.SSHPort)
	}
	if !c.AutoUpdate.Enabled {
		t.Error("auto_update lost in the upgrade")
	}
}

// The endpoint must survive the rewrite too — the old block is not written
// back, so a value only held in memory would vanish on the next save.
func TestUpgradedV2ConfigSurvivesSave(t *testing.T) {
	withTempStackctlDir(t)
	writeConfigFile(t, v2File)

	c, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if err := c.Save(); err != nil {
		t.Fatalf("Save: %v", err)
	}

	again, err := Load()
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	if again.Public.Relay.SSHHost != "sish.learningstack.online" || again.Public.Relay.SSHPort != 2222 {
		t.Errorf("relay endpoint lost across save/reload: %+v", again.Public.Relay)
	}
	if again.Public.BaseDomain != "testschulev02.learningstack.online" {
		t.Errorf("base domain lost across save/reload: %q", again.Public.BaseDomain)
	}
}

// A config without any endpoint at all still has to produce a usable one,
// rather than dialling the empty string.
func TestLoadFillsRelayDefaults(t *testing.T) {
	withTempStackctlDir(t)
	writeConfigFile(t, "version: 3\nsetup_state: ready\nschool:\n    slug: phoenix\npublic:\n    transport: relay\n    base_domain: phoenix.learningstack.online\n")

	c, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if c.Public.Relay.SSHHost != DefaultRelaySSHHost || c.Public.Relay.SSHPort != DefaultRelaySSHPort {
		t.Errorf("relay defaults not applied: %+v", c.Public.Relay)
	}
}

// A direct install must not acquire a relay endpoint it has no use for.
func TestLoadLeavesDirectInstallAlone(t *testing.T) {
	withTempStackctlDir(t)
	writeConfigFile(t, "version: 3\nsetup_state: ready\nschool:\n    slug: phoenix\npublic:\n    transport: direct\n    base_domain: ls.gym-phoenix.de\n")

	c, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if c.Public.Relay.SSHHost != "" {
		t.Errorf("direct install got a relay host: %q", c.Public.Relay.SSHHost)
	}
	if c.Public.BaseDomain != "ls.gym-phoenix.de" {
		t.Errorf("BaseDomain = %q — the slug must not override an explicit domain", c.Public.BaseDomain)
	}
}

// A file from a newer build is left as it is. Rewriting it down to this
// build's schema would silently discard whatever that build added.
func TestLoadDoesNotDowngradeNewerConfig(t *testing.T) {
	withTempStackctlDir(t)
	writeConfigFile(t, "version: 99\nsetup_state: ready\nschool:\n    slug: phoenix\npublic:\n    transport: relay\n    base_domain: phoenix.learningstack.online\n")

	c, err := Load()
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if c.Version != 99 {
		t.Errorf("Version = %d, want 99 (unchanged)", c.Version)
	}
}

func writeConfigFile(t *testing.T, content string) {
	t.Helper()
	if err := os.MkdirAll(paths.ConfigDir(), 0o750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(paths.ConfigFile(), []byte(content), 0o640); err != nil {
		t.Fatal(err)
	}
}
