// Package dex generates and manages the dex-config.yaml file that the local
// Dex container reads. stackctl owns this file entirely — it is regenerated
// on every change (app install/remove, setup) and Dex is restarted via
// docker restart ls-dex (< 1s, sessions survive because of SQLite persistence).
//
// The local Dex is the only party that talks to the school's login provider.
// Every app is a static client of it, so installing an app never touches the
// provider. Its own address follows config.public (see internal/public).
package dex

import (
	"fmt"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/lngstck/stackctl/internal/config"
	"github.com/lngstck/stackctl/internal/docker"
	"github.com/lngstck/stackctl/internal/paths"
	"github.com/lngstck/stackctl/internal/public"
)

// DexContainerName is the Docker container name for the local Dex instance.
const DexContainerName = "ls-dex"

// Client represents an OIDC client registered in Dex's staticClients list.
// Each installed app with an oidc: block gets one.
type Client struct {
	ID           string   `yaml:"id"`
	Secret       string   `yaml:"secret"`
	Name         string   `yaml:"name"`
	RedirectURIs []string `yaml:"redirectURIs"`
}

// GenerateConfig builds the full dex-config.yaml content from the current
// school config and list of registered OIDC clients. The caller is
// responsible for writing it to disk and restarting Dex.
func GenerateConfig(cfg *config.Config, clients []Client) ([]byte, error) {
	authURL := public.AuthURL(cfg)

	doc := map[string]any{
		"issuer": authURL,
		"storage": map[string]any{
			"type": "sqlite3",
			"config": map[string]any{
				"file": "/data/dex.db",
			},
		},
		"web": map[string]any{
			"http": "0.0.0.0:5556",
		},
		"oauth2": map[string]any{
			"skipApprovalScreen": true,
			"responseTypes":      []string{"code"},
		},
		// Token/session expiry — keeps the SQLite store from growing forever.
		// Auth-Request + Device-Request are short-lived UX windows. Refresh
		// tokens bound the maximum session length regardless of activity.
		"expiry": map[string]any{
			"signingKeys":    "6h",
			"idTokens":       "24h",
			"authRequests":   "24h",
			"deviceRequests": "5m",
			"refreshTokens": map[string]any{
				"disableRotation":   false,
				"reuseInterval":     "30s",
				"validIfNotUsedFor": "2160h", // 90d inactivity window
				"absoluteLifetime":  "4320h", // 180d max session
			},
		},
	}

	// No login provider is connected yet, so Dex's own password database is
	// the only way in: it holds the test accounts the admin creates. Dex also
	// refuses to start without any connector at all, and an empty password
	// database counts as one — so it stays enabled even without accounts.
	doc["enablePasswordDB"] = true
	if passwords := staticPasswords(cfg.Auth.TestAccounts); len(passwords) > 0 {
		doc["staticPasswords"] = passwords
	}

	// Static clients: one per OIDC app.
	if len(clients) > 0 {
		var staticClients []any
		for _, c := range clients {
			staticClients = append(staticClients, map[string]any{
				"id":           c.ID,
				"secret":       c.Secret,
				"name":         c.Name,
				"redirectURIs": c.RedirectURIs,
			})
		}
		doc["staticClients"] = staticClients
	}

	data, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("dex: marshal config: %w", err)
	}

	header := "# Generated by stackctl – do not edit manually.\n"
	return append([]byte(header), data...), nil
}

// staticPasswords renders test accounts as Dex password entries, shaped to
// the claims contract (internal/claims): the random ID becomes the subject,
// the name the name claim, and the role the only groups value.
func staticPasswords(accounts []config.TestAccount) []any {
	var out []any
	for _, a := range accounts {
		username, _, _ := strings.Cut(a.Login, "@")
		out = append(out, map[string]any{
			"email":             a.Login,
			"hash":              a.PasswordHash,
			"username":          a.Name,
			"name":              a.Name,
			"preferredUsername": username,
			"userID":            a.ID,
			"groups":            []string{a.Role},
		})
	}
	return out
}

// SaveConfig writes dex-config.yaml to disk and restarts the Dex container.
// This is the main entry point for any Dex config change.
func SaveConfig(cfg *config.Config, clients []Client) error {
	data, err := GenerateConfig(cfg, clients)
	if err != nil {
		return err
	}
	// DexConfigFile lives under LEARNINGSTACK_DIR/dex/config/ so the same
	// host directory that's bind-mounted into /etc/dex contains the file.
	// Dir 0o755 + File 0o644: das Config-Verzeichnis bleibt
	// stackctl-writable (fuer zukuenftige SaveConfig-Aufrufe), und der
	// Dex-Container (uid 1001) kann das File lesen ohne dass wir chownen
	// muessen. Auf einem Single-Tenant-Server kein Sicherheitsproblem —
	// dieselben Secrets liegen in der .env (gleiche Threat-Modellierung).
	if err := paths.EnsureDir(filepath.Dir(paths.DexConfigFile()), 0o755); err != nil {
		return err
	}
	if err := paths.AtomicWrite(paths.DexConfigFile(), data, 0o644); err != nil {
		return err
	}
	// Restart Dex so it picks up the new config. Sessions survive because
	// Dex stores them in SQLite under /data/dex.db.
	if docker.IsRunning(DexContainerName) {
		if err := docker.RestartContainer(DexContainerName); err != nil {
			return fmt.Errorf("dex: restart after config change: %w", err)
		}
	}
	return nil
}

// AddClient adds or replaces an OIDC client in the list, then saves and
// restarts Dex. Idempotent for the same clientID.
func AddClient(client Client, cfg *config.Config, existingClients []Client) ([]Client, error) {
	updated := make([]Client, 0, len(existingClients)+1)
	replaced := false
	for _, c := range existingClients {
		if c.ID == client.ID {
			updated = append(updated, client)
			replaced = true
		} else {
			updated = append(updated, c)
		}
	}
	if !replaced {
		updated = append(updated, client)
	}
	if err := SaveConfig(cfg, updated); err != nil {
		return nil, err
	}
	return updated, nil
}

// RemoveClient removes an OIDC client by ID, then saves and restarts Dex.
func RemoveClient(clientID string, cfg *config.Config, existingClients []Client) ([]Client, error) {
	updated := make([]Client, 0, len(existingClients))
	for _, c := range existingClients {
		if c.ID != clientID {
			updated = append(updated, c)
		}
	}
	if err := SaveConfig(cfg, updated); err != nil {
		return nil, err
	}
	return updated, nil
}

// BuildRedirectURI builds the full OIDC redirect URI for an app.
//
// When isPublic is true the app's public URL is used; otherwise the LAN URL
// on the server's own address. An OIDC app only works publicly — Dex holds
// exactly one redirect URI per client — so callers pass true for anything
// that has to log in.
func BuildRedirectURI(cfg *config.Config, appID, redirectPath string, port int, isPublic bool) string {
	if isPublic {
		return public.AppURL(cfg, appID) + redirectPath
	}
	domain := cfg.School.ServerDomain
	if domain == "" {
		domain = "localhost"
	}
	return fmt.Sprintf("http://%s:%d%s", domain, port, redirectPath)
}
