// Package dex generates and manages the dex-config.yaml file that the local
// Dex container reads. stackctl owns this file entirely — it is regenerated
// on every change (app install/remove, setup) and Dex is restarted via
// docker restart ls-dex (< 1s, sessions survive because of SQLite persistence).
//
// Phase 1 architecture: the local school Dex connects upstream to the central
// Dex at auth.learningstack.online, which in turn connects to moin.schule.
// No static-password fallback, no Wobila, no upstream switching.
//
// The config uses claimMapping (SINGULAR, not claimMappings!) — see Memory
// project_central_dex_moinschule.md for the critical fallstrick.
package dex

import (
	"fmt"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"github.com/lngstck/stackctl/internal/config"
	"github.com/lngstck/stackctl/internal/docker"
	"github.com/lngstck/stackctl/internal/paths"
)

// DexContainerName is the Docker container name for the local Dex instance.
const DexContainerName = "ls-dex"

// CentralDexIssuer is the OIDC issuer URL of the central Dex that all
// school Dex instances connect to as upstream. Fixed in Phase 1.
const CentralDexIssuer = "https://auth.learningstack.online"

// Client represents an OIDC client registered in Dex's staticClients list.
// Each installed app with an oidc: block gets one.
type Client struct {
	ID           string   `yaml:"id"`
	Secret       string   `yaml:"secret"`
	Name         string   `yaml:"name"`
	RedirectURIs []string `yaml:"redirectURIs"`
}

// GenerateConfig builds the full dex-config.yaml content from the current
// school config and list of registered OIDC clients. The caller is
// responsible for writing it to disk and restarting Dex.
func GenerateConfig(cfg *config.Config, clients []Client) ([]byte, error) {
	authURL := AuthURL(cfg)

	doc := map[string]any{
		"issuer": authURL,
		"storage": map[string]any{
			"type": "sqlite3",
			"config": map[string]any{
				"file": "/data/dex.db",
			},
		},
		"web": map[string]any{
			"http": "0.0.0.0:5556",
		},
		"oauth2": map[string]any{
			"skipApprovalScreen": true,
			"responseTypes":     []string{"code"},
		},
		// Token/session expiry — keeps the SQLite store from growing forever.
		// Auth-Request + Device-Request are short-lived UX windows. Refresh
		// tokens bound the maximum session length regardless of activity.
		"expiry": map[string]any{
			"signingKeys":    "6h",
			"idTokens":       "24h",
			"authRequests":   "24h",
			"deviceRequests": "5m",
			"refreshTokens": map[string]any{
				"disableRotation":   false,
				"reuseInterval":     "30s",
				"validIfNotUsedFor": "2160h", // 90d inactivity window
				"absoluteLifetime":  "4320h", // 180d max session
			},
		},
	}

	// Upstream connector: local Dex → central Dex (→ moin.schule).
	connector := map[string]any{
		"type": "oidc",
		"id":   "central-dex",
		"name": "learningstack",
		"config": map[string]any{
			"issuer":                   CentralDexIssuer,
			"clientID":                 cfg.Dex.ClientID,
			"clientSecret":             cfg.Dex.ClientSecret,
			"redirectURI":              authURL + "/callback",
			"scopes":                   []string{"openid", "profile", "email", "groups"},
			"getUserInfo":              true,
			"insecureSkipEmailVerified": true,
			"insecureEnableGroups":      true,
			// Kein claimMapping: der zentrale Dex liefert email/groups/
			// preferred_username/name bereits korrekt gemappt. Eigene
			// Mappings wuerden den moin.schule-sub (als email) zerstoeren.
		},
	}
	doc["connectors"] = []any{connector}

	// Static clients: one per OIDC app.
	if len(clients) > 0 {
		var staticClients []any
		for _, c := range clients {
			staticClients = append(staticClients, map[string]any{
				"id":           c.ID,
				"secret":       c.Secret,
				"name":         c.Name,
				"redirectURIs": c.RedirectURIs,
			})
		}
		doc["staticClients"] = staticClients
	}

	data, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("dex: marshal config: %w", err)
	}

	header := "# Generated by stackctl – do not edit manually.\n"
	return append([]byte(header), data...), nil
}

// SaveConfig writes dex-config.yaml to disk and restarts the Dex container.
// This is the main entry point for any Dex config change.
func SaveConfig(cfg *config.Config, clients []Client) error {
	data, err := GenerateConfig(cfg, clients)
	if err != nil {
		return err
	}
	// DexConfigFile lives under LEARNINGSTACK_DIR/dex/config/ so the same
	// host directory that's bind-mounted into /etc/dex contains the file.
	if err := paths.EnsureDir(filepath.Dir(paths.DexConfigFile()), 0o750); err != nil {
		return err
	}
	if err := paths.AtomicWrite(paths.DexConfigFile(), data, 0o640); err != nil {
		return err
	}
	// Restart Dex so it picks up the new config. Sessions survive because
	// Dex stores them in SQLite under /data/dex.db.
	if docker.IsRunning(DexContainerName) {
		if err := docker.RestartContainer(DexContainerName); err != nil {
			return fmt.Errorf("dex: restart after config change: %w", err)
		}
	}
	return nil
}

// AddClient adds or replaces an OIDC client in the list, then saves and
// restarts Dex. Idempotent for the same clientID.
func AddClient(client Client, cfg *config.Config, existingClients []Client) ([]Client, error) {
	updated := make([]Client, 0, len(existingClients)+1)
	replaced := false
	for _, c := range existingClients {
		if c.ID == client.ID {
			updated = append(updated, client)
			replaced = true
		} else {
			updated = append(updated, c)
		}
	}
	if !replaced {
		updated = append(updated, client)
	}
	if err := SaveConfig(cfg, updated); err != nil {
		return nil, err
	}
	return updated, nil
}

// RemoveClient removes an OIDC client by ID, then saves and restarts Dex.
func RemoveClient(clientID string, cfg *config.Config, existingClients []Client) ([]Client, error) {
	updated := make([]Client, 0, len(existingClients))
	for _, c := range existingClients {
		if c.ID != clientID {
			updated = append(updated, c)
		}
	}
	if err := SaveConfig(cfg, updated); err != nil {
		return nil, err
	}
	return updated, nil
}

// AuthURL returns the canonical public URL where Dex is reachable.
// This is always https://auth.{slug}.learningstack.online — never a local
// URL, because the OIDC issuer must match between browser and container.
func AuthURL(cfg *config.Config) string {
	return "https://auth." + cfg.School.Slug + ".learningstack.online"
}

// BuildRedirectURI builds the full OIDC redirect URI for an app.
// If tunneled is true, the public tunnel URL is used; otherwise the local URL.
func BuildRedirectURI(redirectPath, appID, schoolSlug, serverDomain string, port int, tunneled bool) string {
	if tunneled {
		return "https://" + appID + "." + schoolSlug + ".learningstack.online" + redirectPath
	}
	return fmt.Sprintf("http://%s:%d%s", serverDomain, port, redirectPath)
}
