package dex

import (
	"strings"
	"testing"

	"gopkg.in/yaml.v3"

	"github.com/lngstck/stackctl/internal/config"
)

func testConfig() *config.Config {
	return &config.Config{
		Version:    config.ConfigVersion,
		SetupState: config.SetupStateReady,
		School: config.School{
			Name:         "Gymnasium Phoenix",
			Slug:         "phoenix",
			ServerDomain: "192.168.1.10",
		},
		Public: config.Public{
			Transport:  config.TransportRelay,
			BaseDomain: "phoenix.learningstack.online",
		},
		Dex: config.Dex{
			ClientID:     "phoenix",
			ClientSecret: "deadbeef1234567890abcdef1234567890abcdef",
		},
	}
}

func TestGenerateConfigBasic(t *testing.T) {
	cfg := testConfig()
	clients := []Client{
		{
			ID:           "langflow",
			Secret:       "abc123",
			Name:         "Langflow",
			RedirectURIs: []string{"https://langflow.phoenix.learningstack.online/oauth/callback"},
		},
	}

	data, err := GenerateConfig(cfg, clients)
	if err != nil {
		t.Fatalf("GenerateConfig: %v", err)
	}
	content := string(data)

	// Banner.
	if !strings.HasPrefix(content, "# Generated by stackctl") {
		t.Error("banner missing")
	}

	// Parse to verify structure.
	var doc map[string]any
	if err := yaml.Unmarshal(data, &doc); err != nil {
		t.Fatalf("invalid YAML: %v\n%s", err, content)
	}

	// Issuer.
	if doc["issuer"] != "https://auth.phoenix.learningstack.online" {
		t.Errorf("issuer = %v", doc["issuer"])
	}

	// Storage.
	storage := doc["storage"].(map[string]any)
	if storage["type"] != "sqlite3" {
		t.Errorf("storage type = %v", storage["type"])
	}

	// Connector: central-dex upstream.
	connectors := doc["connectors"].([]any)
	if len(connectors) != 1 {
		t.Fatalf("connectors count = %d", len(connectors))
	}
	conn := connectors[0].(map[string]any)
	if conn["id"] != "central-dex" {
		t.Errorf("connector id = %v", conn["id"])
	}
	connCfg := conn["config"].(map[string]any)
	if connCfg["issuer"] != CentralDexIssuer {
		t.Errorf("connector issuer = %v", connCfg["issuer"])
	}
	if connCfg["clientID"] != "phoenix" {
		t.Errorf("clientID = %v", connCfg["clientID"])
	}
	if connCfg["redirectURI"] != "https://auth.phoenix.learningstack.online/callback" {
		t.Errorf("redirectURI = %v", connCfg["redirectURI"])
	}

	// Kein claimMapping: Claims laufen vom zentralen Dex (der seinerseits
	// moin.schule mappt) unveraendert durch. Eigene Mappings hier wuerden
	// email (= moin.schule sub, stabiler Identifier) zerstoeren.
	if _, ok := connCfg["claimMapping"]; ok {
		t.Error("claimMapping should not be set — central Dex already maps upstream claims")
	}

	// oauth2 settings.
	oauth2 := doc["oauth2"].(map[string]any)
	if oauth2["skipApprovalScreen"] != true {
		t.Errorf("skipApprovalScreen = %v", oauth2["skipApprovalScreen"])
	}

	// Static clients.
	staticClients := doc["staticClients"].([]any)
	if len(staticClients) != 1 {
		t.Fatalf("staticClients count = %d", len(staticClients))
	}
	sc := staticClients[0].(map[string]any)
	if sc["id"] != "langflow" {
		t.Errorf("client id = %v", sc["id"])
	}
}

func TestGenerateConfigNoClients(t *testing.T) {
	cfg := testConfig()
	data, err := GenerateConfig(cfg, nil)
	if err != nil {
		t.Fatalf("GenerateConfig: %v", err)
	}
	var doc map[string]any
	yaml.Unmarshal(data, &doc)
	if _, ok := doc["staticClients"]; ok {
		t.Error("empty clients should omit staticClients block")
	}
}

func TestAddClientIdempotent(t *testing.T) {
	existing := []Client{
		{ID: "langflow", Secret: "old", Name: "Langflow", RedirectURIs: []string{"https://old"}},
	}
	updated := Client{ID: "langflow", Secret: "new", Name: "Langflow v2", RedirectURIs: []string{"https://new"}}

	// We can't call AddClient because it calls SaveConfig (needs docker).
	// Test the replacement logic manually.
	result := make([]Client, 0, len(existing)+1)
	replaced := false
	for _, c := range existing {
		if c.ID == updated.ID {
			result = append(result, updated)
			replaced = true
		} else {
			result = append(result, c)
		}
	}
	if !replaced {
		result = append(result, updated)
	}

	if len(result) != 1 {
		t.Errorf("count = %d, want 1", len(result))
	}
	if result[0].Secret != "new" {
		t.Errorf("secret = %q, want new", result[0].Secret)
	}
}

func TestBuildRedirectURI(t *testing.T) {
	cfg := testConfig()

	// Public URL.
	got := BuildRedirectURI(cfg, "langflow", "/oauth/callback", 8320, true)
	want := "https://langflow.phoenix.learningstack.online/oauth/callback"
	if got != want {
		t.Errorf("BuildRedirectURI public = %q, want %q", got, want)
	}

	// Local URL.
	got = BuildRedirectURI(cfg, "langflow", "/oauth/callback", 8320, false)
	want = "http://192.168.1.10:8320/oauth/callback"
	if got != want {
		t.Errorf("BuildRedirectURI local = %q, want %q", got, want)
	}
}

// A school on its own domain must get its apps and its issuer under that
// domain — this is the regression the pre-v3 string concatenation could not
// express at all.
func TestBuildRedirectURICustomDomain(t *testing.T) {
	cfg := testConfig()
	cfg.Public.BaseDomain = "ls.gym-phoenix.de"

	got := BuildRedirectURI(cfg, "pylearn", "/auth/callback", 8330, true)
	want := "https://pylearn.ls.gym-phoenix.de/auth/callback"
	if got != want {
		t.Errorf("BuildRedirectURI = %q, want %q", got, want)
	}
}
