package llm

import (
	"errors"
	"fmt"
	"os"
	"regexp"
	"sort"

	"gopkg.in/yaml.v3"

	"github.com/lngstck/stackctl/internal/paths"
)

// slugRE entspricht der Erwartung von llmd (s. llmd/internal/config/config.go).
// Wenn das Pattern sich aendert, BEIDE Stellen anpassen.
var slugRE = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]*$`)

// ValidSlug pruef ein Slug fuer Provider/Persona/Key-IDs.
func ValidSlug(s string) bool {
	return slugRE.MatchString(s)
}

// header wird allen geschriebenen YAML-Files vorangestellt.
const header = "# Generated by stackctl — do not edit manually.\n"

// Load liest config.yaml von der Festplatte. Existiert die Datei nicht,
// wird eine leere File zurueckgegeben (frischer Zustand, version 2).
func Load() (*File, error) {
	path := paths.LLMConfigFile()
	raw, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return &File{Version: CurrentVersion}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var f File
	if err := yaml.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if f.Version == "" {
		f.Version = CurrentVersion
	}
	return &f, nil
}

// Save schreibt config.yaml atomar und erzwingt CurrentVersion.
func Save(f *File) error {
	f.Version = CurrentVersion
	sortAll(f)

	data, err := yaml.Marshal(f)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	out := append([]byte(header), data...)
	// 0644 weil llmd-Container (uid 1001 in der Regel) das File lesen muss.
	// API-Keys sind Klartext — Risiko-Posture siehe llmd ARCHITECTURE.md §3.
	if err := paths.AtomicWrite(paths.LLMConfigFile(), out, 0o644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// sortAll bringt Listen in deterministische Reihenfolge — wichtig fuer
// reproduzierbare Diffs und Tests.
func sortAll(f *File) {
	sort.Slice(f.Providers, func(i, j int) bool { return f.Providers[i].ID < f.Providers[j].ID })
	sort.Slice(f.Personas, func(i, j int) bool { return f.Personas[i].ID < f.Personas[j].ID })
	sort.Slice(f.APIKeys, func(i, j int) bool { return f.APIKeys[i].ID < f.APIKeys[j].ID })
	for i := range f.APIKeys {
		sort.Strings(f.APIKeys[i].AllowedPersonas)
	}
}

// === CRUD: Providers ===

// AddProvider fuegt einen Provider hinzu. ID muss eindeutig + valid slug sein.
// APIKey darf leer sein (Admin fuellt nachtraeglich) — Personas auf so einem
// Provider bleiben dann llmd-seitig "inactive" bis der Key da ist.
func (f *File) AddProvider(p Provider) error {
	if !ValidSlug(p.ID) {
		return fmt.Errorf("invalid provider id %q (must be lowercase slug)", p.ID)
	}
	if p.BaseURL == "" {
		return fmt.Errorf("provider %q: base_url required", p.ID)
	}
	if p.Kind == "" {
		p.Kind = "openai"
	}
	for _, ex := range f.Providers {
		if ex.ID == p.ID {
			return fmt.Errorf("provider %q already exists", p.ID)
		}
	}
	f.Providers = append(f.Providers, p)
	return nil
}

// SetProviderKey setzt den API-Key eines Providers (leer = entfernen).
// Convenience-Helper fuer die UI: separater Endpunkt fuer "Key rotieren",
// damit der Endpunkt nicht den ganzen Provider neu schicken muss.
func (f *File) SetProviderKey(id, key string) error {
	for i := range f.Providers {
		if f.Providers[i].ID == id {
			f.Providers[i].APIKey = key
			return nil
		}
	}
	return fmt.Errorf("provider %q not found", id)
}

// RemoveProvider entfernt einen Provider. Schlaegt fehl, wenn noch Personas
// auf ihn referenzieren — Aufrufer muss die zuerst entfernen / umhaengen.
func (f *File) RemoveProvider(id string) error {
	for _, p := range f.Personas {
		if p.Provider == id {
			return fmt.Errorf("provider %q is still referenced by persona %q", id, p.ID)
		}
	}
	for i, p := range f.Providers {
		if p.ID == id {
			f.Providers = append(f.Providers[:i], f.Providers[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("provider %q not found", id)
}

// GetProvider findet einen Provider per ID.
func (f *File) GetProvider(id string) *Provider {
	for i := range f.Providers {
		if f.Providers[i].ID == id {
			return &f.Providers[i]
		}
	}
	return nil
}

// === CRUD: Personas ===

// AddPersona fuegt eine Persona hinzu. Provider darf leer sein (z.B. fuer
// Seed-Personas, die der Admin spaeter zuordnet); ist er gesetzt, muss er
// existieren und ein upstream_id mitgeliefert werden.
func (f *File) AddPersona(p Persona) error {
	if !ValidSlug(p.ID) {
		return fmt.Errorf("invalid persona id %q", p.ID)
	}
	if p.Provider != "" {
		if f.GetProvider(p.Provider) == nil {
			return fmt.Errorf("persona %q references unknown provider %q", p.ID, p.Provider)
		}
		if p.UpstreamID == "" {
			return fmt.Errorf("persona %q: upstream_id required when provider is set", p.ID)
		}
	}
	for _, ex := range f.Personas {
		if ex.ID == p.ID {
			return fmt.Errorf("persona %q already exists", p.ID)
		}
	}
	f.Personas = append(f.Personas, p)
	return nil
}

// RemovePersona entfernt die Persona. Removed-API-Keys behalten den
// Persona-Verweis in allowed_personas — schadet nicht (Persona existiert
// nicht mehr, also kein Zugriff).
func (f *File) RemovePersona(id string) error {
	for i, p := range f.Personas {
		if p.ID == id {
			f.Personas = append(f.Personas[:i], f.Personas[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("persona %q not found", id)
}

func (f *File) GetPersona(id string) *Persona {
	for i := range f.Personas {
		if f.Personas[i].ID == id {
			return &f.Personas[i]
		}
	}
	return nil
}

// SetPersonaUpstream weist einer Persona einen Provider + Upstream-ID zu.
// Beide leer = Persona zurueck auf "inactive".
func (f *File) SetPersonaUpstream(personaID, provider, upstreamID string) error {
	p := f.GetPersona(personaID)
	if p == nil {
		return fmt.Errorf("persona %q not found", personaID)
	}
	if provider != "" {
		if f.GetProvider(provider) == nil {
			return fmt.Errorf("provider %q not found", provider)
		}
		if upstreamID == "" {
			return fmt.Errorf("upstream_id required when provider is set")
		}
	}
	p.Provider = provider
	p.UpstreamID = upstreamID
	return nil
}

// SetPersonaPrompt setzt den inline System-Prompt einer Persona (leer = keiner).
func (f *File) SetPersonaPrompt(personaID, prompt string) error {
	p := f.GetPersona(personaID)
	if p == nil {
		return fmt.Errorf("persona %q not found", personaID)
	}
	p.Prompt = prompt
	return nil
}

// === CRUD: API Keys ===

func (f *File) AddAPIKey(k APIKey) error {
	if !ValidSlug(k.ID) {
		return fmt.Errorf("invalid key id %q", k.ID)
	}
	if k.Prefix == "" || k.Hash == "" {
		return fmt.Errorf("key %q: prefix and hash required", k.ID)
	}
	for _, ex := range f.APIKeys {
		if ex.ID == k.ID {
			return fmt.Errorf("key %q already exists", k.ID)
		}
		if ex.Prefix == k.Prefix {
			return fmt.Errorf("key prefix %q collides with existing key %q", k.Prefix, ex.ID)
		}
	}
	f.APIKeys = append(f.APIKeys, k)
	return nil
}

func (f *File) RemoveAPIKey(id string) error {
	for i, k := range f.APIKeys {
		if k.ID == id {
			f.APIKeys = append(f.APIKeys[:i], f.APIKeys[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("key %q not found", id)
}

func (f *File) GetAPIKey(id string) *APIKey {
	for i := range f.APIKeys {
		if f.APIKeys[i].ID == id {
			return &f.APIKeys[i]
		}
	}
	return nil
}
