package llm

import (
	"errors"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/lngstck/stackctl/internal/paths"
)

// slugRE entspricht der Erwartung von llmd (s. llmd/internal/config/config.go).
// Wenn das Pattern sich aendert, BEIDE Stellen anpassen.
var slugRE = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]*$`)

// ValidSlug pruef ein Slug fuer Provider/Model/Persona/Key-IDs.
func ValidSlug(s string) bool {
	return slugRE.MatchString(s)
}

// header wird allen geschriebenen YAML-Files vorangestellt.
const header = "# Generated by stackctl — do not edit manually.\n"

// Load liest config.yaml von der Festplatte. Existiert die Datei nicht,
// wird eine leere File zurueckgegeben (frischer Zustand, version 1).
// Prompts werden NICHT geladen — die liegen als eigene Dateien neben
// config.yaml und werden separat behandelt.
func Load() (*File, error) {
	path := paths.LLMConfigFile()
	raw, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return &File{Version: CurrentVersion}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	var f File
	if err := yaml.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	if f.Version == "" {
		f.Version = CurrentVersion
	}
	return &f, nil
}

// Save schreibt config.yaml atomar und erzwingt CurrentVersion.
// Prompt-Dateien werden NICHT angefasst — die haben eigene Setter.
func Save(f *File) error {
	f.Version = CurrentVersion
	sortAll(f)

	data, err := yaml.Marshal(f)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}
	out := append([]byte(header), data...)
	// 0644 weil llmd-Container (uid 1001 in der Regel) das File lesen muss.
	// Der eigentliche Secret-Wert (bcrypt-Hashes) ist gehasht, nicht reversibel.
	if err := paths.AtomicWrite(paths.LLMConfigFile(), out, 0o644); err != nil {
		return fmt.Errorf("write config: %w", err)
	}
	return nil
}

// sortAll bringt Listen in deterministische Reihenfolge — wichtig fuer
// reproduzierbare Diffs und Tests.
func sortAll(f *File) {
	sort.Slice(f.Providers, func(i, j int) bool { return f.Providers[i].ID < f.Providers[j].ID })
	sort.Slice(f.Models, func(i, j int) bool { return f.Models[i].ID < f.Models[j].ID })
	sort.Slice(f.Personas, func(i, j int) bool { return f.Personas[i].ID < f.Personas[j].ID })
	sort.Slice(f.APIKeys, func(i, j int) bool { return f.APIKeys[i].ID < f.APIKeys[j].ID })
	for i := range f.APIKeys {
		sort.Strings(f.APIKeys[i].AllowedPersonas)
	}
}

// === Prompts ===

// LoadPrompt liest den System-Prompt einer Persona. Liefert "" zurueck,
// wenn die Datei nicht existiert (z.B. Persona ohne Prompt).
func LoadPrompt(personaID string) (string, error) {
	raw, err := os.ReadFile(paths.LLMPromptFile(personaID))
	if errors.Is(err, os.ErrNotExist) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("read prompt %s: %w", personaID, err)
	}
	return string(raw), nil
}

// SavePrompt schreibt den System-Prompt einer Persona atomar.
// Trailing newline wird normalisiert (genau eine).
func SavePrompt(personaID, content string) error {
	if !ValidSlug(personaID) {
		return fmt.Errorf("invalid persona id %q", personaID)
	}
	content = strings.TrimRight(content, "\n") + "\n"
	return paths.AtomicWrite(paths.LLMPromptFile(personaID), []byte(content), 0o644)
}

// RemovePrompt loescht die Prompt-Datei einer Persona. Idempotent.
func RemovePrompt(personaID string) error {
	err := os.Remove(paths.LLMPromptFile(personaID))
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	return err
}

// === CRUD: Providers ===

// AddProvider fuegt einen Provider hinzu. ID muss eindeutig + valid slug sein.
func (f *File) AddProvider(p Provider) error {
	if !ValidSlug(p.ID) {
		return fmt.Errorf("invalid provider id %q (must be lowercase slug)", p.ID)
	}
	if p.BaseURL == "" {
		return fmt.Errorf("provider %q: base_url required", p.ID)
	}
	if p.APIKeyEnv == "" {
		return fmt.Errorf("provider %q: api_key_env required", p.ID)
	}
	if p.Kind == "" {
		p.Kind = "openai"
	}
	for _, ex := range f.Providers {
		if ex.ID == p.ID {
			return fmt.Errorf("provider %q already exists", p.ID)
		}
	}
	f.Providers = append(f.Providers, p)
	return nil
}

// RemoveProvider entfernt einen Provider. Schlaegt fehl, wenn noch Modelle
// auf ihn referenzieren — Aufrufer muss die zuerst entfernen.
func (f *File) RemoveProvider(id string) error {
	for _, m := range f.Models {
		if m.Provider == id {
			return fmt.Errorf("provider %q is still referenced by model %q", id, m.ID)
		}
	}
	for i, p := range f.Providers {
		if p.ID == id {
			f.Providers = append(f.Providers[:i], f.Providers[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("provider %q not found", id)
}

// GetProvider findet einen Provider per ID.
func (f *File) GetProvider(id string) *Provider {
	for i := range f.Providers {
		if f.Providers[i].ID == id {
			return &f.Providers[i]
		}
	}
	return nil
}

// === CRUD: Models ===

func (f *File) AddModel(m Model) error {
	if !ValidSlug(m.ID) {
		return fmt.Errorf("invalid model id %q", m.ID)
	}
	if m.UpstreamID == "" {
		return fmt.Errorf("model %q: upstream_id required", m.ID)
	}
	if f.GetProvider(m.Provider) == nil {
		return fmt.Errorf("model %q references unknown provider %q", m.ID, m.Provider)
	}
	for _, ex := range f.Models {
		if ex.ID == m.ID {
			return fmt.Errorf("model %q already exists", m.ID)
		}
	}
	f.Models = append(f.Models, m)
	return nil
}

func (f *File) RemoveModel(id string) error {
	for _, p := range f.Personas {
		if p.Model == id {
			return fmt.Errorf("model %q is still referenced by persona %q", id, p.ID)
		}
	}
	for i, m := range f.Models {
		if m.ID == id {
			f.Models = append(f.Models[:i], f.Models[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("model %q not found", id)
}

func (f *File) GetModel(id string) *Model {
	for i := range f.Models {
		if f.Models[i].ID == id {
			return &f.Models[i]
		}
	}
	return nil
}

// === CRUD: Personas ===

func (f *File) AddPersona(p Persona) error {
	if !ValidSlug(p.ID) {
		return fmt.Errorf("invalid persona id %q", p.ID)
	}
	if p.Model != "" && f.GetModel(p.Model) == nil {
		return fmt.Errorf("persona %q references unknown model %q", p.ID, p.Model)
	}
	for _, ex := range f.Personas {
		if ex.ID == p.ID {
			return fmt.Errorf("persona %q already exists", p.ID)
		}
	}
	// PromptFile default: <id>.md
	if p.PromptFile == "" {
		p.PromptFile = p.ID + ".md"
	}
	f.Personas = append(f.Personas, p)
	return nil
}

// RemovePersona entfernt die Persona und (falls vorhanden) ihre Prompt-Datei.
// Removed-API-Keys behalten den Persona-Verweis in allowed_personas —
// das schadet nicht (Persona existiert nicht mehr, also kein Zugriff).
// Optional: ueber CleanupOrphanedPermissions kann aufgeraeumt werden.
func (f *File) RemovePersona(id string) error {
	for i, p := range f.Personas {
		if p.ID == id {
			f.Personas = append(f.Personas[:i], f.Personas[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("persona %q not found", id)
}

func (f *File) GetPersona(id string) *Persona {
	for i := range f.Personas {
		if f.Personas[i].ID == id {
			return &f.Personas[i]
		}
	}
	return nil
}

// SetPersonaModel weist einer Persona ein Modell zu (oder "" zum Deaktivieren).
func (f *File) SetPersonaModel(personaID, modelID string) error {
	p := f.GetPersona(personaID)
	if p == nil {
		return fmt.Errorf("persona %q not found", personaID)
	}
	if modelID != "" && f.GetModel(modelID) == nil {
		return fmt.Errorf("model %q not found", modelID)
	}
	p.Model = modelID
	return nil
}

// === CRUD: API Keys ===

func (f *File) AddAPIKey(k APIKey) error {
	if !ValidSlug(k.ID) {
		return fmt.Errorf("invalid key id %q", k.ID)
	}
	if k.Prefix == "" || k.Hash == "" {
		return fmt.Errorf("key %q: prefix and hash required", k.ID)
	}
	for _, ex := range f.APIKeys {
		if ex.ID == k.ID {
			return fmt.Errorf("key %q already exists", k.ID)
		}
		if ex.Prefix == k.Prefix {
			return fmt.Errorf("key prefix %q collides with existing key %q", k.Prefix, ex.ID)
		}
	}
	f.APIKeys = append(f.APIKeys, k)
	return nil
}

func (f *File) RemoveAPIKey(id string) error {
	for i, k := range f.APIKeys {
		if k.ID == id {
			f.APIKeys = append(f.APIKeys[:i], f.APIKeys[i+1:]...)
			return nil
		}
	}
	return fmt.Errorf("key %q not found", id)
}

func (f *File) GetAPIKey(id string) *APIKey {
	for i := range f.APIKeys {
		if f.APIKeys[i].ID == id {
			return &f.APIKeys[i]
		}
	}
	return nil
}
