package llm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lngstck/stackctl/internal/paths"
)

// setupTmpDir verbiegt LEARNINGSTACK_DIR auf ein t.TempDir() und gibt das
// llmd-Config-Verzeichnis zurueck. Aufrufer braucht sich um Cleanup nicht
// kuemmern — t.Setenv setzt am Test-Ende zurueck.
func setupTmpDir(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	t.Setenv(paths.EnvLearningstackDir, root)
	return filepath.Join(root, "llmd", "config")
}

func TestValidSlug(t *testing.T) {
	cases := map[string]bool{
		"openai":       true,
		"gpt-4o-mini":  true,
		"minimax-m2.5": true,
		"a":            true,
		"a1":           true,
		"a_b":          true,
		"":             false,
		"-bad":         false,
		"BAD":          false,
		".bad":         false,
		"with/slash":   false,
		"with space":   false,
		"with$dollar":  false,
	}
	for in, want := range cases {
		if got := ValidSlug(in); got != want {
			t.Errorf("ValidSlug(%q) = %v, want %v", in, got, want)
		}
	}
}

func TestLoadMissingReturnsEmpty(t *testing.T) {
	setupTmpDir(t)
	f, err := Load()
	if err != nil {
		t.Fatalf("Load on missing file: %v", err)
	}
	if f.Version != CurrentVersion {
		t.Errorf("version = %q, want %q", f.Version, CurrentVersion)
	}
	if len(f.Providers) != 0 || len(f.Personas) != 0 {
		t.Errorf("expected empty file, got %+v", f)
	}
}

func TestRoundtrip(t *testing.T) {
	configDir := setupTmpDir(t)

	f := &File{}
	mustNoErr(t, f.AddProvider(Provider{ID: "openai", Kind: "openai", BaseURL: "https://api.openai.com", APIKey: "sk-test"}))
	mustNoErr(t, f.AddPersona(Persona{
		ID:         "schnell",
		Provider:   "openai",
		UpstreamID: "gpt-4o-mini",
		Prompt:     "Du bist hilfreich.\n",
		Params:     map[string]any{"temperature": 0.4},
	}))
	mustNoErr(t, f.AddAPIKey(APIKey{ID: "open-webui", Prefix: "llm-abc12345", Hash: "$2a$12$x"}))

	if err := Save(f); err != nil {
		t.Fatalf("Save: %v", err)
	}

	data, err := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if !strings.HasPrefix(string(data), "# Generated by stackctl") {
		t.Errorf("missing header: %s", string(data[:60]))
	}

	got, err := Load()
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	if len(got.Providers) != 1 || got.Providers[0].ID != "openai" || got.Providers[0].APIKey != "sk-test" {
		t.Errorf("provider roundtrip: %+v", got.Providers)
	}
	if len(got.Personas) != 1 {
		t.Fatalf("persona count = %d", len(got.Personas))
	}
	p := got.Personas[0]
	if p.Provider != "openai" || p.UpstreamID != "gpt-4o-mini" || !strings.HasPrefix(p.Prompt, "Du bist hilfreich") {
		t.Errorf("persona roundtrip: %+v", p)
	}
}

func TestAddProviderDuplicate(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	mustNoErr(t, f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKey: "y"}))
	if err := f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKey: "y"}); err == nil {
		t.Error("expected duplicate error")
	}
}

func TestAddProviderAllowsEmptyKey(t *testing.T) {
	// Admin darf einen Provider ohne Key anlegen und ihn spaeter via
	// SetProviderKey nachreichen. Personas darauf bleiben llmd-seitig
	// inaktiv bis der Key da ist.
	setupTmpDir(t)
	f := &File{}
	if err := f.AddProvider(Provider{ID: "openai", BaseURL: "https://x"}); err != nil {
		t.Errorf("empty key should be allowed at stackctl layer: %v", err)
	}
}

func TestSetProviderKey(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "openai", BaseURL: "x"})
	if err := f.SetProviderKey("openai", "sk-new"); err != nil {
		t.Fatalf("set: %v", err)
	}
	if f.GetProvider("openai").APIKey != "sk-new" {
		t.Errorf("key not set")
	}
	if err := f.SetProviderKey("ghost", "x"); err == nil {
		t.Error("expected not-found")
	}
}

func TestRemoveProviderBlockedByPersona(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKey: "y"})
	_ = f.AddPersona(Persona{ID: "p1", Provider: "openai", UpstreamID: "u"})
	if err := f.RemoveProvider("openai"); err == nil {
		t.Error("expected block from referencing persona")
	}
}

func TestAddPersonaUnknownProvider(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	if err := f.AddPersona(Persona{ID: "p1", Provider: "ghost", UpstreamID: "u"}); err == nil {
		t.Error("expected unknown-provider error")
	}
}

func TestAddPersonaRequiresUpstreamWhenProviderSet(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKey: "y"})
	if err := f.AddPersona(Persona{ID: "p1", Provider: "openai"}); err == nil {
		t.Error("expected upstream_id required error")
	}
}

func TestAddPersonaWithoutProviderOK(t *testing.T) {
	// Persona ohne Provider ist explizit erlaubt — sie ist dann inaktiv,
	// llmd zeigt sie nicht in /v1/models. Wichtig fuer Seed-Personas, die
	// erst spaeter vom Admin zugeordnet werden.
	setupTmpDir(t)
	f := &File{}
	if err := f.AddPersona(Persona{ID: "p1"}); err != nil {
		t.Errorf("expected no error, got %v", err)
	}
}

func TestSetPersonaUpstream(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKey: "y"})
	_ = f.AddPersona(Persona{ID: "p1"})

	if err := f.SetPersonaUpstream("p1", "openai", "gpt-4o"); err != nil {
		t.Fatalf("set: %v", err)
	}
	p := f.GetPersona("p1")
	if p.Provider != "openai" || p.UpstreamID != "gpt-4o" {
		t.Errorf("not set: %+v", p)
	}

	// Auf "" zuruecksetzen = deaktivieren
	if err := f.SetPersonaUpstream("p1", "", ""); err != nil {
		t.Fatalf("unset: %v", err)
	}
	if f.GetPersona("p1").Provider != "" {
		t.Errorf("provider not cleared")
	}

	// provider gesetzt, upstream leer => Fehler
	if err := f.SetPersonaUpstream("p1", "openai", ""); err == nil {
		t.Error("expected upstream-required error")
	}
	// unbekannter Provider => Fehler
	if err := f.SetPersonaUpstream("p1", "ghost", "u"); err == nil {
		t.Error("expected unknown-provider error")
	}
}

func TestSetPersonaPrompt(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddPersona(Persona{ID: "p1"})
	if err := f.SetPersonaPrompt("p1", "Du bist freundlich."); err != nil {
		t.Fatal(err)
	}
	if f.GetPersona("p1").Prompt != "Du bist freundlich." {
		t.Errorf("prompt not set")
	}
	// Leer ist erlaubt (= Passthrough)
	if err := f.SetPersonaPrompt("p1", ""); err != nil {
		t.Fatal(err)
	}
	if f.GetPersona("p1").Prompt != "" {
		t.Errorf("prompt not cleared")
	}
}

func TestAPIKeyPrefixCollision(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddAPIKey(APIKey{ID: "a", Prefix: "llm-xxx", Hash: "h"})
	if err := f.AddAPIKey(APIKey{ID: "b", Prefix: "llm-xxx", Hash: "h"}); err == nil {
		t.Error("expected prefix collision")
	}
}

func TestSaveSortsListsDeterministically(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "zzz", BaseURL: "x", APIKey: "y"})
	_ = f.AddProvider(Provider{ID: "aaa", BaseURL: "x", APIKey: "y"})
	if err := Save(f); err != nil {
		t.Fatal(err)
	}
	got, _ := Load()
	if got.Providers[0].ID != "aaa" || got.Providers[1].ID != "zzz" {
		t.Errorf("not sorted: %+v", got.Providers)
	}
}

func mustNoErr(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
