package llm

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/lngstck/stackctl/internal/paths"
)

// setupTmpDir verbiegt LEARNINGSTACK_DIR auf ein t.TempDir() und gibt das
// llmd-Config-Verzeichnis zurueck. Aufrufer braucht sich um Cleanup nicht
// kuemmern — t.Setenv setzt am Test-Ende zurueck.
func setupTmpDir(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	t.Setenv(paths.EnvLearningstackDir, root)
	return filepath.Join(root, "llmd", "config")
}

func TestValidSlug(t *testing.T) {
	cases := map[string]bool{
		"openai":          true,
		"gpt-4o-mini":     true,
		"minimax-m2.5":    true,
		"a":               true,
		"a1":              true,
		"a_b":             true,
		"":                false,
		"-bad":            false,
		"BAD":             false,
		".bad":            false,
		"with/slash":      false,
		"with space":      false,
		"with$dollar":     false,
	}
	for in, want := range cases {
		if got := ValidSlug(in); got != want {
			t.Errorf("ValidSlug(%q) = %v, want %v", in, got, want)
		}
	}
}

func TestLoadMissingReturnsEmpty(t *testing.T) {
	setupTmpDir(t)
	f, err := Load()
	if err != nil {
		t.Fatalf("Load on missing file: %v", err)
	}
	if f.Version != CurrentVersion {
		t.Errorf("version = %q, want %q", f.Version, CurrentVersion)
	}
	if len(f.Providers) != 0 || len(f.Personas) != 0 {
		t.Errorf("expected empty file, got %+v", f)
	}
}

func TestRoundtrip(t *testing.T) {
	configDir := setupTmpDir(t)

	f := &File{}
	mustNoErr(t, f.AddProvider(Provider{ID: "openai", Kind: "openai", BaseURL: "https://api.openai.com", APIKeyEnv: "PROVIDER_OPENAI_KEY"}))
	mustNoErr(t, f.AddModel(Model{ID: "gpt-4o-mini", Provider: "openai", UpstreamID: "gpt-4o-mini"}))
	mustNoErr(t, f.AddPersona(Persona{ID: "schnell", Model: "gpt-4o-mini", Params: map[string]any{"temperature": 0.4}}))
	mustNoErr(t, f.AddAPIKey(APIKey{ID: "open-webui", Prefix: "llm-abc12345", Hash: "$2a$12$x"}))

	if err := Save(f); err != nil {
		t.Fatalf("Save: %v", err)
	}

	// File da, header da, content da
	data, err := os.ReadFile(filepath.Join(configDir, "config.yaml"))
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	if !strings.HasPrefix(string(data), "# Generated by stackctl") {
		t.Errorf("missing header: %s", string(data[:60]))
	}

	got, err := Load()
	if err != nil {
		t.Fatalf("reload: %v", err)
	}
	if len(got.Providers) != 1 || got.Providers[0].ID != "openai" {
		t.Errorf("provider lost: %+v", got.Providers)
	}
	if len(got.Personas) != 1 || got.Personas[0].PromptFile != "schnell.md" {
		t.Errorf("persona default prompt_file wrong: %+v", got.Personas)
	}
}

func TestAddProviderDuplicate(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	mustNoErr(t, f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKeyEnv: "Y"}))
	if err := f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKeyEnv: "Y"}); err == nil {
		t.Error("expected duplicate error")
	}
}

func TestRemoveProviderBlockedByModel(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKeyEnv: "Y"})
	_ = f.AddModel(Model{ID: "m1", Provider: "openai", UpstreamID: "u"})
	if err := f.RemoveProvider("openai"); err == nil {
		t.Error("expected block from referencing model")
	}
}

func TestRemoveModelBlockedByPersona(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKeyEnv: "Y"})
	_ = f.AddModel(Model{ID: "m1", Provider: "openai", UpstreamID: "u"})
	_ = f.AddPersona(Persona{ID: "p1", Model: "m1"})
	if err := f.RemoveModel("m1"); err == nil {
		t.Error("expected block from referencing persona")
	}
}

func TestAddPersonaUnknownModel(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	if err := f.AddPersona(Persona{ID: "p1", Model: "ghost"}); err == nil {
		t.Error("expected unknown-model error")
	}
}

func TestAddPersonaWithoutModelOK(t *testing.T) {
	// Persona ohne Modell ist explizit erlaubt — sie ist dann inaktiv,
	// llmd zeigt sie nicht in /v1/models.
	setupTmpDir(t)
	f := &File{}
	if err := f.AddPersona(Persona{ID: "p1"}); err != nil {
		t.Errorf("expected no error, got %v", err)
	}
}

func TestSetPersonaModel(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "openai", BaseURL: "x", APIKeyEnv: "Y"})
	_ = f.AddModel(Model{ID: "m1", Provider: "openai", UpstreamID: "u"})
	_ = f.AddPersona(Persona{ID: "p1"})

	if err := f.SetPersonaModel("p1", "m1"); err != nil {
		t.Fatalf("set: %v", err)
	}
	if f.GetPersona("p1").Model != "m1" {
		t.Errorf("model not set")
	}
	// Auf "" zuruecksetzen = deaktivieren
	if err := f.SetPersonaModel("p1", ""); err != nil {
		t.Fatalf("unset: %v", err)
	}
	if f.GetPersona("p1").Model != "" {
		t.Errorf("model not cleared")
	}
	// Ungueltige Referenz schlaegt fehl
	if err := f.SetPersonaModel("p1", "ghost"); err == nil {
		t.Error("expected unknown-model error")
	}
}

func TestAPIKeyPrefixCollision(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddAPIKey(APIKey{ID: "a", Prefix: "llm-xxx", Hash: "h"})
	if err := f.AddAPIKey(APIKey{ID: "b", Prefix: "llm-xxx", Hash: "h"}); err == nil {
		t.Error("expected prefix collision")
	}
}

func TestPromptRoundtrip(t *testing.T) {
	setupTmpDir(t)
	if err := SavePrompt("p1", "Hallo Welt\n"); err != nil {
		t.Fatalf("save: %v", err)
	}
	got, err := LoadPrompt("p1")
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if got != "Hallo Welt\n" {
		t.Errorf("content: %q", got)
	}
}

func TestPromptNewlineNormalisation(t *testing.T) {
	setupTmpDir(t)
	// Mehrfache trailing newlines werden auf eine reduziert.
	if err := SavePrompt("p1", "Inhalt\n\n\n"); err != nil {
		t.Fatal(err)
	}
	got, _ := LoadPrompt("p1")
	if got != "Inhalt\n" {
		t.Errorf("newline norm failed: %q", got)
	}
	// Ohne newline am Ende — eine wird ergaenzt.
	_ = SavePrompt("p2", "Ohne")
	got2, _ := LoadPrompt("p2")
	if got2 != "Ohne\n" {
		t.Errorf("no-newline norm failed: %q", got2)
	}
}

func TestPromptMissing(t *testing.T) {
	setupTmpDir(t)
	got, err := LoadPrompt("missing")
	if err != nil {
		t.Fatalf("expected no error for missing, got %v", err)
	}
	if got != "" {
		t.Errorf("expected empty, got %q", got)
	}
}

func TestPromptInvalidSlug(t *testing.T) {
	setupTmpDir(t)
	if err := SavePrompt("../etc/passwd", "boom"); err == nil {
		t.Error("expected slug validation to block path traversal")
	}
}

func TestRemovePromptIdempotent(t *testing.T) {
	setupTmpDir(t)
	// Auf eine nie-existierende Persona angewendet => kein Fehler.
	if err := RemovePrompt("never-existed"); err != nil {
		t.Errorf("expected idempotent, got %v", err)
	}
	// Erstellen, loeschen, nochmal loeschen — alles ok.
	_ = SavePrompt("p1", "x")
	if err := RemovePrompt("p1"); err != nil {
		t.Errorf("first remove: %v", err)
	}
	if err := RemovePrompt("p1"); err != nil {
		t.Errorf("second remove: %v", err)
	}
}

func TestSaveSortsListsDeterministically(t *testing.T) {
	setupTmpDir(t)
	f := &File{}
	_ = f.AddProvider(Provider{ID: "zzz", BaseURL: "x", APIKeyEnv: "Z"})
	_ = f.AddProvider(Provider{ID: "aaa", BaseURL: "x", APIKeyEnv: "A"})
	if err := Save(f); err != nil {
		t.Fatal(err)
	}
	got, _ := Load()
	if got.Providers[0].ID != "aaa" || got.Providers[1].ID != "zzz" {
		t.Errorf("not sorted: %+v", got.Providers)
	}
}

func mustNoErr(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}
